dbt_repo:
  outputs:
    dev:
      account: hmiduua-ug83971
      database: dev
      password: Test@123456789
      role: Accountadmin
      schema: bronze_airbnb
      threads: 1
      type: snowflake
      user: vik
      warehouse: compute_wh
  target: dev
sales_project:
  outputs:
    dev:
      account: pbxrknu-ha66177
      database: demo_dbt_db
      password: Test@123
      role: ACCOUNTADMIN
      schema: demo_dbt_sch
      threads: 4
      type: snowflake
      user: vicky
      warehouse: COMPUTE_WH
  target: dev
